id: include('type_id')
supertypes: list(include('type_id'), required=False)
description: str()
deprecated: bool(required=False)
attributes: list(include('attribute'), required=False)
resources: list(include('resource'), required=False)

---
type_id: regex('^csmim\\.obj\\.[a-z0-9\\-.]+\\.\\d+$')

attribute:
  key: str()
  optional: bool(required=False)
  description: str()

resource:
  id: regex('^[A-Za-z0-9\\-._~]+$')
  mode: any('r', 'w', 'rw', 'x')
  racc: bool(required=False)
  attributes: list(include('attribute'), required=False)
  parameters: list(include('dict_item'), required=False)
  type: include('data_type')
  description: str()
  unit: str(required=False)
  optional: bool(required=False)
  enum-values: list(include('enum_value'), required=False)
  array-items: include('array_item', required=False)
  dict-items: list(include('dict_item'), required=False)

enum_value:
  key: int(min=0)
  name: str()
  description: str(required=False)

array_item:
  description: str(required=False)
  unit: str(required=False)
  enum-values: list(include('enum_value'), required=False)
  array-items: include('array_item', required=False)
  dict-items: list(include('dict_item'), required=False)

dict_item:
  key: str()
  type: include('data_type')
  description: str(required=False)
  unit: str(required=False)
  optional: bool(required=False)
  enum-values: list(include('enum_value'), required=False)
  array-items: include('array_item', required=False)
  dict-items: list(include('dict_item'), required=False)

data_type: enum(
  'void',
  'raw',
  'bool', 'bool[]',
  'int', 'int[]', 'int[][]',
  'uint', 'uint[]', 'uint[][]',
  'float', 'float[]', 'float[][]',
  'string', 'string[]', 'string[][]',
  'bytes', 'bytes[]',
  'enum', 'enum[]',
  'utc', 'utc[]',
  'dict', 'dict[]')
