name: check-yaml-syntax
run-name: YAML syntax check for ${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  yamllint:
    name: Check YAML syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: YAML lint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_config_filepath: '.yamllint'
          yamllint_file_or_dir: 'types'
          yamllint_strict: true
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
