name: check-csmim-syntax
run-name: CSMIM syntax check for ${{ github.actor }}
on: [push]
jobs:
  check-csmim-object:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt
      - name: Test with pytest
        run: |
          pytest .github/workflows/test-csmim-syntax.py -v