id: regex('^csmim\\.obj\\.[a-z0-9\\-.]+\\.\\d+$')
supertypes: list(matches=regex('^csmim\\.obj\\.[a-z0-9\\-.]+\\.\\d+$'), required=False)
description: str()
deprecated: bool(required=False)
attributes: list(include('attribute'), required=False)
resources: list(include('resource'), required=False)

---
attribute:
  key: str()
  mandatory: bool(required=False)
  description: str()

parameter:
  key: str()
  type: enum(
    'void',
    'raw',
    'bool', 'bool[]',
    'int', 'int[]',
    'uint', 'uint[]',
    'float','float[]',
    'string','string[]',
    'bytes','bytes[]',
    'enum','enum[]',
    'utc','utc[]',
    'dict','dict[]',
    required=False)
  optional: bool(required=False)
  description: str()

resource:
  id: str()
  mode: any('r', 'w', 'rw', 'x')
  type: enum(
    'void',
    'raw',
    'bool', 'bool[]',
    'int', 'int[]',
    'uint', 'uint[]',
    'float','float[]',
    'string','string[]',
    'bytes','bytes[]',
    'enum','enum[]',
    'utc','utc[]',
    'dict','dict[]')
  mandatory: bool(required=False)
  description: str()
  enum-values: map(required=False)
  parameters: list(include('parameter'), required=False)

